apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./k8s/*
build:
  local:
    push: false
  artifacts:
    - image: emjot13/backend
      context: backend
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/*.js"
            dest: .
    - image: emjot13/frontend
      context: frontend
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .