apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
spec:
  storageClassName: manual
  capacity:
    storage: 128Mi
  accessModes:
   - ReadWriteOnce
  hostPath:
   path: "/etc/db"
   type: DirectoryOrCreate