#zad1 -->  sudo docker run --publish 4200:80 nginx

FROM busybox
CMD ["echo", "Hello from my dockerfile"]


# FROM alpine:3.14
# COPY ./index.html /usr/share/nginx/html 
# COPY nginx.conf /etc/nginx/
# EXPOSE 4200
# CMD ["nginx", "-g", "daemon off;"]
# RUN apk add --no-cache nginx.conf
# ENTRYPOINT [ "executable" ]


# CMD echo "seeeeima"

# docker build -t name .
# docker run -it alpine nginx