version: '3'

services:
  api:
    build:
      dockerfile: /home/emjot13/Desktop/studia/technologieChmurowe/lab6/compose/backend/Dockerfile
      context: /home/emjot13/Desktop/studia/technologieChmurowe/lab6/compose
    environment:
      - /home/emjot13/Desktop/studia/technologieChmurowe/lab6/compose
    ports:
      - "8000:5000"